# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# ЗАДАНИЕ 1 - альтернативная реализация с использованием heapq
import heapq

class PriorityQueue:
    def __init__(self, get_priority):
        self.get_priority = get_priority
        self.heap = []
        self.counter = 0
    
    def add(self, item):
        # heapq реализует min-heap, поэтому для max-heap используем отрицательный приоритет
        priority = -self.get_priority(item)
        heapq.heappush(self.heap, (priority, self.counter, item))
        self.counter += 1
    
    def poll(self):
        if self.heap:
            return heapq.heappop(self.heap)[2]
        return None

# проверка
print("-ЗАДАНИЕ 1-")
q = PriorityQueue(lambda x: len(x))
q.add("a")
q.add("abc")
q.add("ab")
print(q.poll())  # abc
print(q.poll())  # ab
print(q.poll())  # a

# ЗАДАНИЕ 2 - другой подход с использованием функций-оберток

class Animal:
    def __init__(self, name):
        self.name = name
    
    def __repr__(self):
        return f"{self.__class__.__name__}({self.name})"

class Dog(Animal):
    def voice(self):
        return "Гав!"

class Cat(Animal):
    def voice(self):
        return "Мяу!"

# Копирует только собак (используем filter)
def copyAnimals(source, destination):
    dogs = list(filter(lambda x: isinstance(x, Dog), source))
    destination.extend(dogs)

# Заполняет тремя котами (альтернативный способ)
def fillWithCats(target_list):
    target_list.clear()
    target_list += [Cat("Мурзик"), Cat("Барсик"), Cat("Рыжик")]

# Безопасный перенос (с использованием слайсов)
def safeTransfer(source, destination):
    destination[len(destination):] = source[:]  # расширенный срез
    source[:] = []  # очистка через срез

# проверка
print("\n-ЗАДАНИЕ 2-")

# проверка copyAnimals
dogs_list = [Dog("Рекс"), Dog("Джек")]
animals_list = [Cat("Снежок")]
copyAnimals(dogs_list, animals_list)
print(f"После copyAnimals: {[a.name for a in animals_list]}")

# проверка fillWithCats
cats_only = [Dog("Тузик")]
fillWithCats(cats_only)
print(f"После fillWithCats: {[a.name for a in cats_only]}")

# проверка safeTransfer
source_list = [Dog("Гром"), Dog("Молния")]
dest_list = [Cat("Луна")]
safeTransfer(source_list, dest_list)
print(f"После safeTransfer source: {[s.name for s in source_list]}")
print(f"После safeTransfer dest: {[d.name for d in dest_list]}")